from __future__ import annotations


def _parse_codes(multiline_csv: str) -> list[str]:
    normalized = multiline_csv.replace("\n", ",")
    return [code.strip().upper() for code in normalized.split(",") if code.strip()]


# Seed airports requested by user for hub-pool connectivity expansion.
HUB_CONNECTIVITY_SEEDS = _parse_codes(
    """
    ACA,AMD,ANU,ASA,ASW,ATQ,ATZ,AUA,AXA,AZS,BGI,BHO,BKK,BLB,BOM,BRX,BZE,CAI,CCU,CEB,CEI,CEN,CIX,CME
    CMW,CNX,CPE,CRK,CTM,CUL,CUN,CVM,CXR,CYB,CYO,CZA,CZM,DAD,DAV,DEL,DJE,DKR,DMK,DOM,DPS,DSS,DVO,EIS
    FDF,FOR,FPO,GAE,GAF,GAN,GAU,GCM,GDT,GES,GGT,GND,GOU,GSQ,GYE,GYM,HAN,HAV,HDY,HKT,HMB,HOG,HPH,HRG
    HUX,HYD,ILO,JAI,JBQ,JIB,JPA,KBV,KIN,KLO,KOS,LAO,LAP,LBJ,LGP,LIR,LKO,LMM,LOP,LOV,LPQ,LRM,LTO,LXR
    MAA,MAM,MBJ,MEC,MHH,MID,MLE,MNL,MSW,MTY,MZT,NAG,NAS,NAT,NEV,NLD,NTR,OZZ,PAC,PIU,PKZ,PLS,PNH,POP
    PQC,PQM,PTP,PTY,PUJ,PVR,PXM,RAK,REC,REP,REX,RIH,RMF,SAL,SCU,SDQ,SFA,SFG,SFS,SGN,SJD,SJO,SJU,SKB
    SKV,SSA,SSH,STI,SVD,SYQ,TAM,TAP,TCP,TGZ,TOE,UNI,USM,UTP,UVF,VCA,VCL,VER,VRA,VSA,VTE,VVI,ZAM,ZIH
    ZLO
    """
)

# Expanded one-hop hub candidate pool: every airport with a direct route to/from any seed airport.
AUTO_HUB_CANDIDATES = _parse_codes(
    """
    ABJ,ABS,ABV,ACA,ACC,ACU,ADD,ADE,ADL,ADZ,AGA,AGR,AGU,AHB,AJL,AJU,AKL,ALA,ALG,AMD,AMM,AMS,ANU,ARN
    ASA,ASB,ASM,ASU,ASW,ATC,ATH,ATL,ATQ,ATZ,AUA,AUH,AUS,AXA,AXP,AZS,BAH,BAQ,BBI,BBO,BCD,BCN,BCV,BDL
    BDO,BDQ,BEL,BEN,BEY,BFQ,BFV,BGA,BGI,BGW,BGY,BHJ,BHM,BHO,BHU,BHX,BJL,BJX,BKI,BKK,BKO,BLA,BLB,BLR
    BMU,BMV,BNE,BOC,BOD,BOG,BOM,BON,BOS,BPN,BPS,BRA,BRS,BRU,BRX,BSB,BSL,BSO,BTH,BUD,BVA,BWI,BWN,BXU
    BZE,CAH,CAI,CAN,CAP,CAY,CBB,CBO,CCC,CCJ,CCS,CCU,CDG,CEB,CEI,CEN,CGH,CGK,CGM,CGN,CGO,CGP,CGY,CHX
    CIA,CIX,CJB,CJM,CJS,CKG,CKY,CLE,CLO,CLT,CMB,CME,CMH,CMN,CMW,CNF,CNX,COK,COO,COR,CPE,CPH,CPV,CPX
    CRI,CRK,CRL,CRM,CSK,CSX,CTG,CTM,CTS,CTU,CUC,CUE,CUK,CUL,CUN,CUR,CUU,CVG,CVM,CWB,CXR,CYB,CYO,CYP
    CYZ,CZA,CZM,DAC,DAD,DAR,DAV,DCA,DED,DEL,DEN,DFW,DGA,DGT,DHM,DIB,DIL,DIN,DIR,DIU,DJE,DKR,DLA,DLE
    DLI,DME,DMK,DMM,DMU,DOH,DOM,DPL,DPS,DRK,DRS,DRV,DRW,DSS,DTW,DUB,DUS,DVO,DWC,DXB,DYU,EBB,EBL,EIN
    EIS,ELH,ELQ,ENE,ESM,EWR,EZE,FCO,FDF,FEN,FLL,FNA,FOC,FON,FOR,FPO,FRA,FRS,FUK,FVM,GAE,GAF,GAN,GAO
    GAU,GCM,GDL,GDT,GEO,GES,GGT,GHB,GHE,GIG,GKK,GLA,GLF,GND,GNM,GOI,GOP,GOU,GPS,GRO,GRU,GSQ,GUA,GUM
    GVA,GWL,GYE,GYM,HAH,HAM,HAN,HAV,HBE,HBX,HDY,HEA,HEL,HGA,HGH,HGN,HHN,HKG,HKT,HMB,HMO,HND,HNL,HOD
    HOE,HOG,HPH,HRG,HRI,HUI,HUX,HYD,IAD,IAH,IAO,ICN,IDR,IGA,IKA,IKT,ILO,IMF,IND,IOS,IQQ,IQT,ISB,IST
    IXA,IXB,IXC,IXD,IXE,IXJ,IXL,IXM,IXR,IXS,IXU,IXZ,JAI,JAX,JBQ,JDH,JDO,JED,JFK,JGA,JHG,JIB,JLR,JNB
    JOG,JOL,JPA,JQE,JUB,KAN,KBL,KBP,KBV,KDH,KDM,KDO,KHH,KHI,KHN,KIN,KIX,KJA,KKC,KLO,KMG,KNU,KOE,KOP
    KOS,KRT,KTM,KUL,KUU,KWE,KWI,KWL,LAD,LAO,LAP,LAS,LAX,LAZ,LBJ,LCA,LCE,LEC,LED,LEJ,LGA,LGI,LGP,LGW
    LHE,LHR,LIL,LIM,LIR,LIS,LKO,LMM,LOE,LOH,LOP,LOS,LOV,LPA,LPB,LPQ,LPT,LRM,LSP,LTN,LTO,LTX,LUH,LUX
    LXG,LXR,LYB,LYS,MAA,MAD,MAM,MAN,MAO,MAQ,MAR,MAZ,MBJ,MBT,MCI,MCO,MCT,MCZ,MDE,MDL,MDW,MEC,MED,MEL
    MEX,MFM,MGA,MGQ,MHH,MIA,MID,MKE,MLE,MLG,MLH,MNL,MOF,MPH,MPP,MRA,MRS,MRU,MSP,MSW,MTY,MUC,MVD,MXP
    MYG,MYY,MZT,NAG,NAS,NAT,NAW,NBE,NBO,NCE,NCL,NDJ,NEV,NGB,NGO,NKC,NLD,NNG,NNT,NOB,NRN,NRT,NSI,NST
    NTE,NTR,NUE,NYT,OAX,ODY,OGL,OGM,ONT,ORD,ORY,OSL,OTD,OUA,OVB,OXB,OZC,OZZ,PAC,PAG,PAP,PAT,PAV,PAZ
    PBC,PBD,PBH,PBI,PBM,PEI,PEK,PEN,PER,PHB,PHE,PHL,PHS,PHX,PIT,PIU,PJM,PKZ,PLJ,PLM,PLS,PMV,PMZ,PNH
    PNQ,PNZ,POA,POM,POP,POS,PPS,PQC,PQM,PRH,PSA,PTP,PTY,PUE,PUJ,PUS,PVE,PVG,PVR,PXM,PXU,PYC,PYY,PZU
    QRO,RAI,RAJ,RAK,RCY,RDU,REC,REP,REX,RGN,RIC,RIH,RIY,RJA,RMF,RMQ,ROI,ROR,RPR,RSD,RTB,RTM,RUH,RUN
    RXS,SAH,SAL,SAN,SAP,SAT,SAX,SBH,SCL,SCU,SCY,SDQ,SDU,SFA,SFG,SFO,SFS,SGN,SHJ,SHL,SIC,SIN,SJC,SJD
    SJI,SJO,SJU,SKB,SKV,SLC,SLP,SLU,SLX,SLZ,SML,SNA,SNO,SNU,SPR,SQS,SRE,SRG,SSA,SSH,STI,STL,STN,STT
    STV,STX,SUB,SUG,SVD,SVO,SVQ,SVX,SWA,SXB,SXF,SXM,SXR,SYD,SYQ,SZB,SZG,SZX,TAB,TAC,TAG,TAI,TAM,TAO
    TAP,TAS,TBB,TBI,TCP,TCR,TDX,TFN,TGU,TGZ,THD,THE,THS,TIF,TIJ,TIM,TIP,TIR,TJA,TLC,TLS,TLV,TMC,TMU
    TNA,TNO,TNR,TOE,TPA,TPE,TRC,TRV,TRZ,TST,TTQ,TUF,TUG,TUN,TUU,TXL,TZA,UBP,UDR,UIH,UIO,ULN,UNI,UNN
    UPG,URT,USM,USU,UTH,UTP,UVF,VCA,VCL,VCP,VCS,VDC,VDH,VER,VGA,VIE,VII,VIJ,VIX,VKG,VKO,VLN,VNS,VQS
    VRA,VRC,VSA,VTE,VTZ,VVI,WGP,WNP,WNZ,WUH,XCR,XIY,XKH,XMN,XQP,XSC,YEG,YHZ,YNB,YQB,YUL,YVR,YYC,YYZ
    ZAM,ZIG,ZIH,ZLO,ZRH,ZSA,ZVK
    """
)
