"""Shared constants for service, provider, and utility layers."""

from __future__ import annotations

SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24
SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY

OUTBOUND_TIME_PROXY_BASE_HOURS = 6
OUTBOUND_TIME_PROXY_TRANSFER_PENALTY_HOURS = 4
OUTBOUND_TIME_PROXY_BASE_SECONDS = OUTBOUND_TIME_PROXY_BASE_HOURS * SECONDS_PER_HOUR
OUTBOUND_TIME_PROXY_TRANSFER_PENALTY_SECONDS = (
    OUTBOUND_TIME_PROXY_TRANSFER_PENALTY_HOURS * SECONDS_PER_HOUR
)
FASTEST_OBJECTIVE_PRICE_MULTIPLIER = 0.01
BEST_OBJECTIVE_PRICE_PER_HOUR_WEIGHT = 12.0
PRICE_TIME_SCORE_PRICE_WEIGHT = 0.72
PRICE_TIME_SCORE_TIME_WEIGHT = 0.28
INNER_RETURN_BUNDLE_DISCOUNT_FACTOR = 0.67
PRICE_SENTINEL = 10**12

DEFAULT_SERVER_HOST = "127.0.0.1"
DEFAULT_SERVER_PORT = 8000
SERVER_READY_URL_TEMPLATE = "FlightFinder Engine running at http://{host}:{port}"
ROOT_INDEX_PATH = "/index.html"
API_SEARCH_PATH = "/api/search"
API_PROVIDER_CONFIG_PATH = "/api/provider-config"
API_SEARCH_JOBS_PATH = "/api/search-jobs"
HTTP_CACHE_CONTROL_NO_STORE = "no-store, max-age=0, must-revalidate"
HTTP_PRAGMA_NO_CACHE = "no-cache"
HTTP_EXPIRES_IMMEDIATELY = "0"
ERROR_UNKNOWN_ENDPOINT = "Unknown endpoint"
ERROR_UNKNOWN_SEARCH_JOB = "Unknown search job"
ERROR_INVALID_JSON_BODY = "Invalid JSON body"
ERROR_TOO_MANY_RUNNING_SEARCHES = (
    "Too many searches are already running. Wait for one to finish and try again."
)

DEFAULT_SEARCH_JOB_TTL_SECONDS = SECONDS_PER_HOUR
SEARCH_STATUS_QUEUED = "queued"
SEARCH_STATUS_RUNNING = "running"
SEARCH_STATUS_COMPLETED = "completed"
SEARCH_STATUS_FAILED = "failed"
SEARCH_EVENT_QUEUED = "Search queued."
SEARCH_EVENT_COMPLETE = "Search complete."
SEARCH_EVENT_FAILURE_PREFIX = "Search failed: "
SEARCH_EVENT_REQUEST_ACCEPTED = "Search request accepted."
SEARCH_EVENT_STARTED = "Search started."
